---
- name: Copy artifact
  become: yes
  copy:
    src: artifact.tar.gz
    dest: ~/

- name: "extract artifact"
  become: yes
  shell: |
    tar -xvzf ~/artifact.tar.gz

- name: install nodejs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Remove all processes"
  become: yes
  command: pm2 delete all

- name: "start app"
  become: yes
  command: pm2 start npm --start
