---
- name: "extract artifact"
  command: tar xzf backend/artifact.tar.gz
  apt:
    update_cache: yes

- name: install nodejs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "stop default"
  become: yes
  command: pm2 stop default

- name: "start app"
  become: yes
  command: pm2 start npm --start
